sudo: required
services:
    - docker

before_install:
    - docker build -t fiofanow/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true fiofanow/docker-react npm run test -- --coverage

deploy:
    provider: azure_web_apps
    verbose: true
    slot: hello
